GET http://localhost:9520/wiki/hello
Accept: text/html,application/json
###


GET http://localhost:9520/wiki/ebook/list?categoryId2 = 101

###
//不带参数就是类似等同于page=0,怎么论证 ？ 如果将page加上Min(value=1),运行下边测试脚本
//,可以看到的底下提示"rejectedValue": 0,
GET http://localhost:9520/wiki/ebook/list

###


POST http://localhost:8880/ebook/save
Content-Type: application/json

###

GET http://localhost:9520/wiki/category/list


###
GET http://localhost:9520/wiki/redis/get/name

###

GET http://localhost:9520/wiki/redis/set/name/123444
